/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.donor.login;

import java.sql.*;
import DBConnector.DBConnector;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class update1 extends javax.swing.JFrame {

    /**
     * Creates new form update1
     *
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;

    public update1() {
        initComponents();
        conn = DBConnector.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lbldonorId = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jtxtCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtFather = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtMother = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtDob = new javax.swing.JTextField();
        jtxtMob = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtGender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtBlood = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaddress = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jBtnClose = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 60, 710, 10));

        lbldonorId.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lbldonorId.setForeground(new java.awt.Color(255, 255, 255));
        lbldonorId.setText("Donor ID :");
        getContentPane().add(lbldonorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 86, -1));

        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 100, -1));

        jBtnSearch.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/donor/login/Pictures/BBMS ICON/search1.png"))); // NOI18N
        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 388, 700, 10));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Full Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 138, 91, -1));

        jtxtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCityActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 190, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Father Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 178, -1, -1));
        getContentPane().add(jtxtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 178, 180, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mother Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 218, 108, -1));
        getContentPane().add(jtxtMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 218, 180, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Birth");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 258, -1, -1));

        jtxtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDobActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 258, 180, -1));
        getContentPane().add(jtxtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 298, 180, -1));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 338, 76, -1));

        jtxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGenderActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 338, 180, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Blood Group");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, -1));

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Complete Address");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 138, 180, -1));

        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 190, -1));

        jtxtBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBloodActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 190, -1));

        jtxtaddress.setColumns(20);
        jtxtaddress.setRows(5);
        jScrollPane1.setViewportView(jtxtaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 200, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 122, 700, 10));

        jBtnClose.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jBtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/donor/login/Pictures/BBMS ICON/Exit application.png"))); // NOI18N
        jBtnClose.setText("Close");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jBtnUpdate.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jBtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/donor/login/Pictures/BBMS ICON/save.png"))); // NOI18N
        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jBtnReset.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jBtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/donor/login/Pictures/BBMS ICON/Update details.png"))); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mobile No");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 298, 84, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/donor/login/Pictures/update-donor.gif"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCityActionPerformed

    private void jtxtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDobActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBloodActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        setVisible(false);
        new update1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
//       Search donor code
        String donorId = jtxtId.getText();

        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select  *from donor where donor_Id='" + donorId + "'");
            if (rs.next()) {
                jtxtName.setText(rs.getString(2));
                jtxtFather.setText(rs.getString(3));
                jtxtMother.setText(rs.getString(4));
                jtxtDob.setText(rs.getString(5));
                jtxtMob.setText(rs.getString(6));
                jtxtGender.setText(rs.getString(7));
                jtxtEmail.setText(rs.getString(8));
                jtxtBlood.setText(rs.getString(9));
                jtxtCity.setText(rs.getString(10));
                jtxtaddress.setText(rs.getString(11));
                jtxtId.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Donor Id does not exist");

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jtxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGenderActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        String donorId = jtxtId.getText();
        String name = jtxtName.getText();
        String motherName = jtxtMother.getText();
        String fatherName = jtxtFather.getText();
        String dob = jtxtDob.getText();
        String mobileNo = jtxtMob.getText();
        String gender = jtxtGender.getText();
        String email = jtxtEmail.getText();
        String bloodGroup = jtxtBlood.getText();
        String city = jtxtCity.getText();
        String address = jtxtaddress.getText();

        try {
            Statement st = conn.createStatement();
            st.executeUpdate("update donor set name='" + name +"' ,father_name='"+fatherName +"' ,mother_name='" +motherName +"',dob='" +   dob +"',mobile_no='" + mobileNo + "',gender='" + gender + "',email='" + email + "',blood_group='" + bloodGroup + "',city='" + city + "',address='" + address + "'where donor_id='"+donorId+"'");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new update1().setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Error");

        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jtxtBlood;
    private javax.swing.JTextField jtxtCity;
    private javax.swing.JTextField jtxtDob;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFather;
    private javax.swing.JTextField jtxtGender;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtMob;
    private javax.swing.JTextField jtxtMother;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextArea jtxtaddress;
    private javax.swing.JLabel lbldonorId;
    // End of variables declaration//GEN-END:variables
}
